import { Ionicons } from "@react-native-vector-icons/ionicons";
import { Tabs } from "expo-router";
import { Platform, StyleSheet } from "react-native";

export default function TabsLayout() {
  return (
      <Tabs
            screenOptions={{
                    headerShown: false,

                            tabBarActiveTintColor: "#0F172A",
                                    tabBarInactiveTintColor: "#94A3B8",

                                            tabBarLabelStyle: styles.tabBarLabel,

                                                    tabBarStyle: {
                                                              position: "absolute",
                                                                        left: 16,
                                                                                  right: 16,
                                                                                            bottom: Platform.OS === "ios" ? 18 : 12,

                                                                                                      height: 68,
                                                                                                                borderRadius: 24,

                                                                                                                          backgroundColor: "rgba(255, 255, 255, 0.94)",

                                                                                                                                    borderWidth: StyleSheet.hairlineWidth,
                                                                                                                                              borderColor: "rgba(148, 163, 184, 0.22)",

                                                                                                                                                        shadowColor: "#0F172A",
                                                                                                                                                                  shadowOffset: {
                                                                                                                                                                              width: 0,
                                                                                                                                                                                          height: 8,
                                                                                                                                                                                                    },
                                                                                                                                                                                                              shadowOpacity: 0.08,
                                                                                                                                                                                                                        shadowRadius: 20,

                                                                                                                                                                                                                                  elevation: 10,

                                                                                                                                                                                                                                            paddingTop: 8,
                                                                                                                                                                                                                                                      paddingBottom: Platform.OS === "ios" ? 8 : 6,

                                                                                                                                                                                                                                                                overflow: "hidden",
                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                tabBarItemStyle: {
                                                                                                                                                                                                                                                                                          paddingVertical: 2,
                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                  <Tabs.Screen
                                                                                                                                                                                                                                                                                                                          name="index"
                                                                                                                                                                                                                                                                                                                                  options={{
                                                                                                                                                                                                                                                                                                                                            title: "Dashboard",

                                                                                                                                                                                                                                                                                                                                                      tabBarIcon: ({ color, size, focused }) => (
                                                                                                                                                                                                                                                                                                                                                                  <Ionicons
                                                                                                                                                                                                                                                                                                                                                                                name={focused ? "grid" : "grid-outline"}
                                                                                                                                                                                                                                                                                                                                                                                              size={size}
                                                                                                                                                                                                                                                                                                                                                                                                            color={color}
                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Tabs.Screen
                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="qr"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: "Scan",

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tabBarIcon: ({ color, size, focused }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Ionicons
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name={focused ? "qr-code" : "qr-code-outline"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  size={size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color={color}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Tabs.Screen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="profile"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          options={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: "Profile",

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tabBarIcon: ({ color, size, focused }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Ionicons
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name={focused ? "person" : "person-outline"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size={size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color={color}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Tabs>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tabBarLabel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: "600",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });